### ISSUE TITLE
Buy or build help

### ISSUE THREAD

**Issue by nyok92** [antmicro/sdi-mipi-bridge-hw#1]
Hi, I'am just wondering if there is a place to buy this bridge or any firm that could build it ?
Thanks for your help !

**Comment by pkatarzynski** [comment]
Currently there is no way to buy this board. You can try to build it yourself or hire us on a project basis to build it for you.
We are working on making the board available off the shelf through a partner but this is not available yet. We will let you know when it happens.

**Comment by Luxonis-Brandon** [comment]
We are actually quite interested in integrating this sort of thing onto a DepthAI/OAK baseboard directly.  We are making open-source MIT-licensed hardware as well which seems to be quite complementary actually:
https://github.com/luxonis/depthai-hardware

And it's also Altium based (which some of ANT-Micro boards are).  We'll likely want to combine your Xavier board with some power-over-coax converters for example.  And do the same with our system on module.

Thoughts?

We can also help manufacturing these by the way if that's of interest.  

Thanks,
Brandon
Luxonis // OpenCV Team
